FROM node:20-alpine

WORKDIR /app

# Cache layer : on installe les deps avant de copier le reste du code
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 4200

# --host 0.0.0.0      
# --proxy-config      
# --poll 2000         

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--proxy-config", "proxy.conf.json", "--poll", "2000"]