FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 4200

# --host 0.0.0.0      
# --proxy-config      
# --poll 2000         : force Angular à vérifier les changements de fichiers toutes les 2s
#                        (nécessaire car les événements filesystem natifs ne traversent pas
#                        toujours les bind mounts Docker, notamment sur Mac/Windows)
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--proxy-config", "proxy.conf.json", "--poll", "2000"]