services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      provenance: false
      sbom: false
    container_name: kuber-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app          
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"   
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      provenance: false
      sbom: false
    container_name: kuber-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app         
      - /app/node_modules       
    
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge