"""initial schema

Revision ID: 46772d6e100a
Revises: 
Create Date: 2026-08-07 21:21:10.816305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '46772d6e100a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_counters',
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_name')
    )
    op.create_table('organization',
    sa.Column('id_org', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_org')
    )
    op.create_table('departments',
    sa.Column('id_dept', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id_org'], ),
    sa.PrimaryKeyConstraint('id_dept')
    )
    op.create_table('users',
    sa.Column('id_usr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('departement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departments.id_dept'], ),
    sa.PrimaryKeyConstraint('id_usr')
    )
    op.create_table('audits',
    sa.Column('id_audit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dept_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auditor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('findings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id_usr'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id_dept'], ),
    sa.PrimaryKeyConstraint('id_audit')
    )
    op.create_table('non_conformances',
    sa.Column('id_nc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('dept_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raised_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('raised_at', sa.DateTime(), nullable=False),
    sa.Column('current_state', sa.Enum('RAISED', 'ASSIGNED', 'UNDER_INVESTIGATION', 'CORRECTIVE_ACTION', 'CLOSED', 'REJECTED', name='ncstate'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id_usr'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id_dept'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id_usr'], ),
    sa.PrimaryKeyConstraint('id_nc')
    )
    op.create_table('audit_findings',
    sa.Column('id_finding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id_audit'], ),
    sa.ForeignKeyConstraint(['nc_id'], ['non_conformances.id_nc'], ),
    sa.PrimaryKeyConstraint('id_finding')
    )
    op.create_table('corrective_actions',
    sa.Column('id_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id_usr'], ),
    sa.ForeignKeyConstraint(['nc_id'], ['non_conformances.id_nc'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id_usr'], ),
    sa.PrimaryKeyConstraint('id_action')
    )
    op.create_table('nc_events',
    sa.Column('id_event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_state', sa.Enum('RAISED', 'ASSIGNED', 'UNDER_INVESTIGATION', 'CORRECTIVE_ACTION', 'CLOSED', 'REJECTED', name='ncstate'), nullable=True),
    sa.Column('to_state', sa.Enum('RAISED', 'ASSIGNED', 'UNDER_INVESTIGATION', 'CORRECTIVE_ACTION', 'CLOSED', 'REJECTED', name='ncstate'), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id_usr'], ),
    sa.ForeignKeyConstraint(['nc_id'], ['non_conformances.id_nc'], ),
    sa.PrimaryKeyConstraint('id_event')
    )
    op.create_table('root_causes',
    sa.Column('id_cause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identified_by'], ['users.id_usr'], ),
    sa.ForeignKeyConstraint(['nc_id'], ['non_conformances.id_nc'], ),
    sa.PrimaryKeyConstraint('id_cause')
    )
    op.create_table('sla_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_type', sa.Enum('WARNING', 'BREACHED', 'RESOLVED', name='slaalerttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('read_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nc_id'], ['non_conformances.id_nc'], ),
    sa.ForeignKeyConstraint(['read_by'], ['users.id_usr'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_alerts_is_read'), 'sla_alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_sla_alerts_nc_id'), 'sla_alerts', ['nc_id'], unique=False)
    op.create_index('ix_sla_alerts_unread_visible', 'sla_alerts', ['is_read'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ux_sla_alerts_nc_type_active', 'sla_alerts', ['nc_id', 'alert_type'], unique=True, postgresql_where=sa.text('resolved_at IS NULL AND deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_sla_alerts_nc_type_active', table_name='sla_alerts', postgresql_where=sa.text('resolved_at IS NULL AND deleted_at IS NULL'))
    op.drop_index('ix_sla_alerts_unread_visible', table_name='sla_alerts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_sla_alerts_nc_id'), table_name='sla_alerts')
    op.drop_index(op.f('ix_sla_alerts_is_read'), table_name='sla_alerts')
    op.drop_table('sla_alerts')
    op.drop_table('root_causes')
    op.drop_table('nc_events')
    op.drop_table('corrective_actions')
    op.drop_table('audit_findings')
    op.drop_table('non_conformances')
    op.drop_table('audits')
    op.drop_table('users')
    op.drop_table('departments')
    op.drop_table('organization')
    op.drop_table('id_counters')
    # ### end Alembic commands ###
